#ifndef CAR_OS_SOAD_CFG_H
#define CAR_OS_SOAD_CFG_H

// This file is autogenerated, any hand modifications will be lost!

#include <Platform_Types.h>
#include <TcpIp.h>



typedef struct {
    uint16 rem_skt_id;  /* remote socket id */
    uint16 gen_skt_id;  /* the tool generated id, for verification purposes */
    uint16 skt_grp_id;  /* remote socket group */
    uint16 loc_skt_id;  /* local socket id ref */
    uint16 rem_ip[16];  /* remote ip (ipv6 or ipv4) */
    uint16 rem_port;    /* remote port number */
    TcpIp_ProtocolType protocol;
    TcpIpDomainType domain_type;
} SoAdSocketConnectionType;


#define MAX_SOCKET_CONNS (5)

typedef struct {
    SoAdSocketConnectionType *socon;
} SoAd_ConfigType;


extern const SoAd_ConfigType SoAd_Config;


#endif
