#include <stddef.h>
#include "SoAd_cfg.h"


// This file is autogenerated, any hand modifications will be lost!


const SoAdSocketConnectionType SoAdSocketConnectionConfigs[MAX_SOCKET_CONNS] = {
	{
		/* SoAd Socket Connection - 0 */
		.rem_skt_id = 0,
		.gen_skt_id = 0,
		.skt_grp_id = 0,
		.loc_skt_id = 0,
		.rem_port = 123,
		.protocol = TCPIP_IPPROTO_TCP,
		.domain_type = TCPIP_AF_INET
	},
	{
		/* SoAd Socket Connection - 1 */
		.rem_skt_id = 1,
		.gen_skt_id = 1,
		.skt_grp_id = 0,
		.loc_skt_id = 0,
		.rem_port = 124,
		.protocol = TCPIP_IPPROTO_TCP,
		.domain_type = TCPIP_AF_INET
	},
	{
		/* SoAd Socket Connection - 2 */
		.rem_skt_id = 2,
		.gen_skt_id = 2,
		.skt_grp_id = 0,
		.loc_skt_id = 0,
		.rem_port = 125,
		.protocol = TCPIP_IPPROTO_TCP,
		.domain_type = TCPIP_AF_INET
	},
	{
		/* SoAd Socket Connection - 3 */
		.rem_skt_id = 3,
		.gen_skt_id = 3,
		.skt_grp_id = 1,
		.loc_skt_id = 0,
		.rem_port = 123,
		.protocol = TCPIP_IPPROTO_UDP,
		.domain_type = TCPIP_AF_INET
	},
	{
		/* SoAd Socket Connection - 4 */
		.rem_skt_id = 4,
		.gen_skt_id = 4,
		.skt_grp_id = 1,
		.loc_skt_id = 0,
		.rem_port = 234,
		.protocol = TCPIP_IPPROTO_UDP,
		.domain_type = TCPIP_AF_INET
	},
};


const SoAd_ConfigType SoAd_Config = {
	.socon = &SoAdSocketConnectionConfigs
};

