#include <stddef.h>
#include "SoAd_cfg.h"


// This file is autogenerated, any hand modifications will be lost!


const SoAdSocketConnectionType SoAdSocketConnectionConfigs[SOAD_TOTAL_SOCKET_CONNS] = {
	{
		/* SoAd Socket Connection - 0 */
		.rem_skt_id = 0,
		.gen_skt_id = 0,
		.skt_grp_id = 0,
		.tcpip_skt_id = 0,
		.rem_ip = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.rem_port = 123,
		.protocol = TCPIP_IPPROTO_TCP,
	},
	{
		/* SoAd Socket Connection - 1 */
		.rem_skt_id = 1,
		.gen_skt_id = 1,
		.skt_grp_id = 0,
		.tcpip_skt_id = 0,
		.rem_ip = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.rem_port = 124,
		.protocol = TCPIP_IPPROTO_TCP,
	},
	{
		/* SoAd Socket Connection - 2 */
		.rem_skt_id = 2,
		.gen_skt_id = 2,
		.skt_grp_id = 0,
		.tcpip_skt_id = 0,
		.rem_ip = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.rem_port = 125,
		.protocol = TCPIP_IPPROTO_TCP,
	},
	{
		/* SoAd Socket Connection - 3 */
		.rem_skt_id = 3,
		.gen_skt_id = 3,
		.skt_grp_id = 1,
		.tcpip_skt_id = 0,
		.rem_ip = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.rem_port = 123,
		.protocol = TCPIP_IPPROTO_UDP,
	},
	{
		/* SoAd Socket Connection - 4 */
		.rem_skt_id = 4,
		.gen_skt_id = 4,
		.skt_grp_id = 1,
		.tcpip_skt_id = 0,
		.rem_ip = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.rem_port = 234,
		.protocol = TCPIP_IPPROTO_UDP,
	},
};


const SoAdPduRouteType SoAdPduRouteConfigs[SOAD_TOTAL_PDU_ROUTES] = {
	{
		/* SoAd PDU Route - 0 */
		.tx_pdu_id    = 0,
		.ul_type      = SOAD_UPPER_LAYER_TYPE_IF,
		.pdu_hdr_id   = 0,
		.socon_id     = 0,
		.socon_grp_id = 0,
	},
	{
		/* SoAd PDU Route - 1 */
		.tx_pdu_id    = 1,
		.ul_type      = SOAD_UPPER_LAYER_TYPE_IF,
		.pdu_hdr_id   = 0,
		.socon_id     = 1,
		.socon_grp_id = 0,
	},
	{
		/* SoAd PDU Route - 2 */
		.tx_pdu_id    = 2,
		.ul_type      = SOAD_UPPER_LAYER_TYPE_IF,
		.pdu_hdr_id   = 0,
		.socon_id     = 3,
		.socon_grp_id = 1,
	},
};


const SoAd_ConfigType SoAd_Config = {
	.socon = &SoAdSocketConnectionConfigs
};

