#ifndef CAR_OS_SOAD_CFG_H
#define CAR_OS_SOAD_CFG_H

// This file is autogenerated, any hand modifications will be lost!

#include <Platform_Types.h>
#include <TcpIp.h>


typedef enum {
    SOAD_UPPER_LAYER_TYPE_IF,
    SOAD_UPPER_LAYER_TYPE_TP,
    SOAD_UPPER_LAYER_TYPE_MAX
} SoAdTxUpperLayerType;


typedef struct {
    uint16 tx_pdu_id;
    SoAdTxUpperLayerType ul_type;
    uint16 pdu_hdr_id;
    uint16 socon_id;
    uint16 socon_grp_id;
} SoAdPduRouteType;



typedef struct {
    uint16 rem_skt_id;  /* remote socket id */
    uint16 gen_skt_id;  /* the tool generated id, for verification purposes */
    uint16 skt_grp_id;  /* remote socket group */
    uint16 loc_ipaddr_id;  /* local socket id ref */
    uint16 loc_port;    /* from sock. group */
    uint16 rem_ip[8];  /* remote ip (ipv6 or ipv4) */
    uint16 rem_port;    /* remote port number */
    TcpIp_ProtocolType protocol;
    TcpIpDomainType ip_version;
    boolean is_tcp_server;
} SoAdSocketConnectionType;


#define SOAD_TOTAL_PDU_ROUTES (4)
#define SOAD_TOTAL_SOCKET_CONNS (4)
#define SOAD_SOCK_CONNS_MAX_CFG (0)


typedef struct {
    SoAdSocketConnectionType *socon;
} SoAd_ConfigType;


extern const SoAd_ConfigType SoAd_Config;
extern const SoAdPduRouteType SoAdPduRouteConfigs[SOAD_TOTAL_PDU_ROUTES];
extern const SoAdSocketConnectionType SoAdSocketConnectionConfigs[SOAD_TOTAL_SOCKET_CONNS];


#endif
